# Generated by Django 3.2.5 on 2021-07-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=70)),
                ('subclassification', models.CharField(max_length=20)),
                ('total_number_of_housing_units', models.IntegerField()),
                ('total_energy_consumption', models.IntegerField()),
                ('energy_consumption_per_household', models.IntegerField()),
                ('energy_consumption_per_household_member', models.IntegerField()),
                ('energy_consumption_per_square_foot', models.IntegerField()),
                ('total_energy_expenditures', models.IntegerField()),
                ('energy_expenditure_per_household', models.IntegerField()),
                ('energy_expenditure_per_household_member', models.IntegerField()),
                ('energy_expenditure_per_square_foot', models.IntegerField()),
            ],
        ),
    ]
