# Generated by Django 3.2.5 on 2021-07-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='energy_consumption_per_household',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='energy_consumption_per_household_member',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='energy_consumption_per_square_foot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='energy_expenditure_per_household',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='energy_expenditure_per_household_member',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='energy_expenditure_per_square_foot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='total_energy_consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='total_energy_expenditures',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='total_number_of_housing_units',
            field=models.FloatField(),
        ),
    ]
