# Generated by Django 3.2.5 on 2021-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyapi', '0002_auto_20210710_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='classification',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='subclassification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
